// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7O1nNMsfuDAXvy_daO7aYO0HDp0yz71I',
    appId: '1:1088242086856:android:0f843eded331e847af06fd',
    messagingSenderId: '1088242086856',
    projectId: 'sbselector-app',
    storageBucket: 'sbselector-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQkYVabd_dY8MKnJWC5IsXuKU6LRYS3kw',
    appId: '1:1088242086856:ios:f70587817c9c4e1eaf06fd',
    messagingSenderId: '1088242086856',
    projectId: 'sbselector-app',
    storageBucket: 'sbselector-app.appspot.com',
    iosClientId: '1088242086856-qkqvlifva4uvrkjmh13j012idupd5e3o.apps.googleusercontent.com',
    iosBundleId: 'jp.Thata.sbselector',
  );
}
